### ISSUE TITLE
Setări -> Tastaturi

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-ro/localizare-FirefoxOS#13]
Number = Numeric? 

<Img src="https://cloud.githubusercontent.com/assets/1391451/11250435/2978ab58-8e35-11e5-922d-853281d01402.jpg" width="300" height="550" />

**Comment by cristisilaghi** [comment]
DEX-ul spune că e „un byte, doi byți”. Și-n plus, se folosește în aplicațiile Microsoft și Google.

**Comment by ioana-chiorean** [comment]
@cristisilaghi

**Comment by sn-o-w** [comment]
Am pus „Numerică” peste tot (Tastatură numerică).
