### ISSUE TITLE
Setări

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-ro/localizare-FirefoxOS#14]
USB Storage = Stocare USB 
<Img src="https://cloud.githubusercontent.com/assets/1391451/11250437/29799bbc-8e35-11e5-9a0a-6f9ceadbb6a1.jpg" width="300" height="550" /> 

Homescreens
<Img src="https://cloud.githubusercontent.com/assets/1391451/11250439/297bb820-8e35-11e5-8986-cd4b92ee1250.jpg" width="300" height="550" />

**Comment by sn-o-w** [comment]
Fixat. Următoru' build ar trebui să fie Ok.
