### ISSUE TITLE
Aplicația Contacte

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-ro/localizare-FirefoxOS#15]
Nume și prenume ar fim aiindicat decât nume și nume

<Img src="https://cloud.githubusercontent.com/assets/1391451/11250436/2979bbe2-8e35-11e5-932f-dc8cc09a9a33.jpg" width="300" height="550" />

**Comment by sn-o-w** [comment]
Modificat. Următorul build ar trebui să fie ok.
