### ISSUE TITLE
Mod dezvoltator

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-ro/localizare-FirefoxOS#16]
Partial tradus și cu litere mari?
<Img src="https://cloud.githubusercontent.com/assets/1391451/11250438/297a5e4e-8e35-11e5-851c-ba0204c4f912.jpg" width="300" height="550" /> 

În aplicația Studio:
<Img src="https://cloud.githubusercontent.com/assets/1391451/11250440/297d7570-8e35-11e5-9dcf-4775a2d5f76e.jpg" width="300" height="550" />

**Comment by sn-o-w** [comment]
Textul lipsă de la prima imagine l-am tradus acum. Textele din a doua imagine nu le văd spre traducere.
