### ISSUE TITLE
Ecran principal - Aplicații 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-ro/localizare-FirefoxOS#18]
Aplicația Notes/Notițe? 
<Img src="https://cloud.githubusercontent.com/assets/1391451/11250445/29954060-8e35-11e5-84d6-20fb23fb90ea.jpg" width="300" height="550" /> 

Uneltele specifice 2.5 
<Img src="https://cloud.githubusercontent.com/assets/1391451/11250446/299624ee-8e35-11e5-9f82-89f9de4d28e3.jpg" width="300" height="550" />

**Comment by sn-o-w** [comment]
Ar trebui să fie „Notițe”.
