### ISSUE TITLE
Aplicație Ceas - Ora

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-ro/localizare-FirefoxOS#19]
- [ ] Discuție Ora vs Oră
- [ ] Discuție marți vs Marți

<Img src="https://cloud.githubusercontent.com/assets/1391451/11250447/29aa92bc-8e35-11e5-8e93-f558665e7630.jpg" width="300" height="550" /> 
<Img src="https://cloud.githubusercontent.com/assets/1391451/11250448/29ab8b36-8e35-11e5-99f5-1c12fb9fe256.jpg" width="300" height="550" />

**Comment by sn-o-w** [comment]
Cu „Ora” sunt de-acord. Cu majusculă pentru ziua săptămânii, sincer nu. Pentru că n-am habar ce trebuie să modific și risc să stric textul în alte părți.
