### ISSUE TITLE
E-mail - Categorii standard

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-ro/localizare-FirefoxOS#5]
Categoriile mesaje trimise si șterse nu sunt traduse:

<Img src="https://cloud.githubusercontent.com/assets/1391451/11254383/0928c9fa-8e49-11e5-99e6-c7a5fcbb4360.jpg" width="300" height="550" />

**Comment by sn-o-w** [comment]
Categoriile nu se traduc, pare-se.

**Comment by ioana-chiorean** [comment]
@cristisilaghi am actualizat imaginea. Te uiti pls din nou?

**Comment by sn-o-w** [comment]
Dar nu le pot traduce. Nu sunt nicăieri spre traducere.
