### ISSUE TITLE
Setări de dezvoltator

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-ro/localizare-FirefoxOS#6]
Setările de dezvoltator nu sunt traduse: 

<Img src="https://cloud.githubusercontent.com/assets/1391451/11250427/2944df6c-8e35-11e5-8c26-3158be2afbc3.jpg" width="300" height="550" />

**Comment by sn-o-w** [comment]
N-am asemenea texte spre traducere.

**Comment by ioana-chiorean** [comment]
Era gresita imaginea.. Imi cer scuze. Te uiti te rog din nou?

**Comment by sn-o-w** [comment]
Unele setări de dezvoltator sunt traduse, iar altele nu. Unele dintre textele astea au fost actualizate. Da' n-am idee cum să traduc „Flash repainted area” sau „Low-precision painting”. Sugestii? Poate există texte asemănătoare prin Android.
