### ISSUE TITLE
Setări - Accesibilitare

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-ro/localizare-FirefoxOS#7]
Descrierea opțiunilor pentru Audio și Input nu sunt traduse:

<img src="https://cloud.githubusercontent.com/assets/1391451/11254456/7d20e914-8e49-11e5-8f54-61ef27a17a74.jpg" width="300" height="550" />

**Comment by cristisilaghi** [comment]
Ciudat. Toate sunt traduse în afară de „Flash repainted area” și „Low-precision painting”. Aștept eventual sugestii, nu am habar dacă cumva sunt traduse. Poate cuvinte/texte echivalente prin Android?

**Comment by ioana-chiorean** [comment]
@cristisilaghi am actualizat poza

**Comment by sn-o-w** [comment]
Modificat.
