### ISSUE TITLE
Licența - Obținerea odului sursă

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-ro/localizare-FirefoxOS#8]
Licența ar trebui tradusă în limba română:

<Img src="https://cloud.githubusercontent.com/assets/1391451/11250430/295ef154-8e35-11e5-99e2-ca12443cec1d.jpg" width="300" height="550" />
<Img src="https://cloud.githubusercontent.com/assets/1391451/11250432/295f0c70-8e35-11e5-9496-deaa717721e0.jpg" width="300" height="550" />

**Comment by sn-o-w** [comment]
Nu se poate traduce, documentul nu e pus spre traducere.
